version: '3.9'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "80:80"
    volumes:
      - wordpress:/www/
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - database
    # args:
    #   - MYSQL_PASSWORD=${}
    # environment:
    #   - MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD)
    #   - MYSQL_USER=${MYSQL_USER}
    #   - MYSQL_PASSWORD=MYSQL_PASSWORD
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    ports:
      - "8080:8080"
    networks:
      - database
    volumes:
      - wordpress:/var/www/html/wordpress
  # test:
  #   image: debian
  #   container_name: test
  #   command: sleep infinity
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - database

networks:
  database:
    name: database

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o : "bind"
      device: ${HOME}/data/
