version: '3.9'
services:
  nginx:
    image: nginx:inception
    restart: alway
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress/
    networks:
      - wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_USER_DB=${MYSQL_USER_DB}
        - MYSQL_USER_DB_PASSWORD=${MYSQL_USER_DB_PASSWORD}
    image: mariadb:inception
    container_name: mariadb
    restart: alway
    networks:
      - wordpress
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER_DB=${MYSQL_USER_DB}
      - MYSQL_USER_DB_PASSWORD=${MYSQL_USER_DB_PASSWORD}

  wordpress:
    image: wordpress:inception
    restart: alway
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    networks:
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER_DB=${MYSQL_USER_DB}
      - MYSQL_USER_DB_PASSWORD=${MYSQL_USER_DB_PASSWORD}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}





networks:
  wordpress:

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o : "bind"
      device: /home/psuanpro/data/
