version: '3.9'
services:
  nginx:
    image: nginx:inception
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress/
    networks:
      - wordpress
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:inception
    container_name: mariadb
    networks:
      - wordpress
    # args: when build
    #   - MYSQL_PASSWORD=${}
    # environment: when container run
    #   - MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD)
    #   - MYSQL_USER=${MYSQL_USER}
    #   - MYSQL_PASSWORD=MYSQL_PASSWORD
  wordpress:
    image: wordpress:inception
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    networks:
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress

networks:
  wordpress:

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o : "bind"
      device: /home/psuanpro/data/
