FROM debian:buster

RUN apt update && apt upgrade -y; \
	apt install -y mariadb-client telnet netcat vim php-fpm php-mysql php-curl php-gd php-mbstring php-xml unzip wget curl;

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar; \
	chmod +x wp-cli.phar; \
	mv wp-cli.phar /usr/local/bin/wp-cli;

WORKDIR /var/www/html/wordpress/

COPY ./tools/run.sh .

EXPOSE 9000

CMD ["bash", "run.sh"]
