
FROM debian:buster

RUN apt update && apt upgrade -y; \
	apt install -y bash nginx openssl;

RUN mkdir -p /run/nginx
COPY ./tools/nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key
COPY ./tools/nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
COPY tools/default.conf /etc/nginx/conf.d/default.conf


EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
