# FROM alpine:3.18.0

# RUN apk update && apk upgrade;\
# 	apk add nginx openrc bash; \
# 	adduser -D -g 'www' www; \
# 	mkdir -p /www ;\
# 	chown -R www:www /var/lib/nginx; \
# 	chown -R www:www /www; \
# 	mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig;

# COPY nginx.conf /etc/nginx/nginx.conf

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]

FROM debian:buster

RUN apt update && apt upgrade -y; \
	apt install -y bash nginx openssl; \
	groupadd wordpress_user; \
	useradd -g wordpress_user wordpress_user; \
	mkdir -p /var/www/psuanpro/html; \
	chown -R $USER:$USER /var/www/psuanpro/html; \
	sudo chmod -R 755 /var/www/psuanpro; \
	nano /var/www/psuanpro/html/index.html;

COPY tools/nginx.conf /etc/nginx/nginx.conf

RUN service nginx start;

CMD [ "sleep", "infinity" ]
